### ISSUE TITLE
Hide remote branches automatically

### ISSUE THREAD

**Issue by Shatur95** [stsewd/fzf-checkout.vim#11]
Thank you for the awesome plugin! Is it possible to hide all remote branches that already locally tracked? 
For example, if I have the following:
```
master
origin/master
origin/branch1
branch2
```

Display it like the followining way:

```
master
branch1
branch2
```

And then just execute a simple `checkout` on the items text.

Currently I need to navigate explicitly every time to master instead of `origin/master`. And I need to explicitly press alt+enter to track a remote branch locally. I would prefer this behavior automatically. As a simple checkout in CLI. Can this somehow achieved?

**Comment by stsewd** [comment]
So, I think there are two (or three?) things here.

1. List local branches only

This is simple, I can just provide an argument for it `:GCheckout locals` (it will call `git branch` instead of `git branch --all`) (and maybe also provide `GCheckout remotes`?)


2. List all locals and remotes, but remotes without the remote name (master instead of origin/master)

For this one I think first I'll need to get the branch name of all remotes and then merge that into the locals list (removing duplicates).


@Shatur95  does this command list all branches from remotes as expected? 
`git branch --remote --format "%(refname:strip=3)"`

**Comment by Shatur95** [comment]
> 2. List all locals and remotes, but remotes without the remote name (master instead of origin/master)

I trying to achieve only this one. Sorry if I was unclear!

>  git branch --remote --format "%(refname:strip=3)"

Yes, this command is just what I need. Can I somehow set this arguments? I tried

```vim
let g:fzf_checkout_git_options = '--sort=-committerdate --format "%(refname:strip=3)'
```

But this broke plugin.

**Comment by stsewd** [comment]
> Can I somehow set this arguments?

Currently, no (probably should mention in the docs that you shouldn't override the format option), and that will hide local branches too.

**Comment by Shatur95** [comment]
Maybe provide a boolean plugin option for this case?

**Comment by stsewd** [comment]
Yeah, I'll try to implement this in the next week

**Comment by Shatur95** [comment]
Thanks!

**Comment by Shatur95** [comment]
I can send a PR if you like the idea. Just tell me how you want to name this option :)

**Comment by stsewd** [comment]
Sorry I haven't had time, your help is appreciated! I think maybe `fzf_checkout_hide_remote`? If you have another idea, feel free to just name it!

**Comment by Shatur95** [comment]
Not a problem, will implement at this weekend :)

> I think maybe fzf_checkout_hide_remote?

Yes, good name as for me.

**Comment by hanh090** [comment]
is that better if we support a user input query option (`--query` in fzf), so user can freely extend that by their choice

**Comment by Shatur95** [comment]
This is not exactly what I meant. I suggest displaying absolutely all branches, but without prefixes. This will allow you to do a regular checkout, as it does from the console.

**Comment by Shatur95** [comment]
You could try #12. Let me know if you like this behavior.
