### ISSUE TITLE
Does not work on Vim version 8.0

### ISSUE THREAD

**Issue by scebotari66** [stsewd/fzf-checkout.vim#17]
Thanks, for the great plugin, @stsewd!

I was able to use it successfully on a MacOS machine, but failed to do so on an Ubuntu machine.

I used the same [vimrc](https://github.com/scebotari66/dotfiles/blob/master/vim/.vimrc) file for both.

Here are the errors I get when I execute `GCheckout`:
![image](https://user-images.githubusercontent.com/329976/91036192-96f8b100-e60f-11ea-9078-afc67ed89fc5.png)

**Comment by stsewd** [comment]
Hi, what version of vim are you using?

**Comment by scebotari66** [comment]
8.0

![image](https://user-images.githubusercontent.com/329976/91044830-99aed280-e61e-11ea-896f-816e44e2a660.png)

**Comment by stsewd** [comment]
What version are you using on Mac? I think this is because of https://github.com/stsewd/fzf-checkout.vim/blob/829cf89c041c0f8d4c2fdd0b129644511847a2a7/autoload/fzf_checkout.vim#L3

Const is kind of new I believe. If you run `:const foo = 'bar'` do you get an error?

If that's the case, we can replace const for let to keep it compatible with old versions.

**Comment by scebotari66** [comment]
Will check out later vim version on MacOS, on Ubuntu this is what I get when running `:const foo = 'bar'`:

![image](https://user-images.githubusercontent.com/329976/91047528-e3012100-e622-11ea-9f12-d417519e159e.png)

**Comment by stsewd** [comment]
@scebotari66 let me know if this solves your problem https://github.com/stsewd/fzf-checkout.vim/pull/18

**Comment by scebotari66** [comment]
My MacOS indeed has a newer version - 8.2

I tried the new branch you've created, it is still not working, but there are less errors.

![image](https://user-images.githubusercontent.com/329976/91147178-92400580-e6c0-11ea-9621-b77a83baaab3.png)

**Comment by alexdrupal** [comment]
Ubuntu 19.10, VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 19 2020 13:12:18)

Error detected while processing function fzf_checkout#list:
line    8:
E121: Undefined variable: s:format
E116: Invalid arguments for function printf('%s %s --color=always --sort=refname:short --format=%s %s', g:fzf_checkout_git_bin, l:subcommand, s:format, g:fzf_checkout_git_options)
line   15:
E121: Undefined variable: l:git_cmd
E116: Invalid arguments for function system(l:git_cmd), '\n')
E116: Invalid arguments for function split(system(l:git_cmd), '\n')
line   19:
E121: Undefined variable: l:git_output
E116: Invalid arguments for function <SNR>113_remove_branch
line   20:
E121: Undefined variable: l:git_output
E116: Invalid arguments for function <SNR>113_remove_branch
line   26:
E121: Undefined variable: l:git_output
E116: Invalid arguments for function s:remove_branch(l:git_output, escape(l:previous, '/')))
line   46:
E121: Undefined variable: l:git_output
E116: Invalid arguments for function fzf#wrap( l:name, {   'source': l:git_output,   'sink*': function('s:checkout', [a:type]),   'options': l:options, }, a:bang,))
E116: Invalid arguments for function fzf#run

**Comment by scebotari66** [comment]
Hey @alexdrupal, this occurs on `support-old-versions` branch?

**Comment by stsewd** [comment]
Sorry about this, I may need to research a little the changes between 8.0 and 8.2 a litte more. Does this work for you in vim8?

`:echo 'foo' .. 'bar'`

**Comment by scebotari66** [comment]
No it doesn't:
![image](https://user-images.githubusercontent.com/329976/91413722-327a6380-e854-11ea-997f-18c4b49360f0.png)

Thanks for all the help @stsewd. I can just update to 8.2 and solve the issue for me. If you want, I can assist you further in making it work for 8.0.

**Comment by stsewd** [comment]
> If you want, I can assist you further in making it work for 8.0.

yes please, I don't think it should be too hard to support. Can you give it a try to this branch again? https://github.com/stsewd/fzf-checkout.vim/pull/18 I've removed the usage of `..`

**Comment by scebotari66** [comment]
All working now :fireworks: 
Thanks, @stsewd!

Also tested `alt-enter`, `ctrl-n`, `ctrl-d`, and did not find any issue.
