### ISSUE TITLE
No need to use fzf#vim#grep

### ISSUE THREAD

**Issue by junegunn** [stsewd/fzf-checkout.vim#2]
Since you're providing your own sink function, there's no reason to use  `fzf#vim#grep` from `fzf.vim`. You can just use `fzf#run` and `fzf#wrap` from the main fzf repo simplifying the code and the dependencies.

- https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun
- https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap

**Comment by stsewd** [comment]
Thanks for the suggestion!
