### ISSUE TITLE
Rebase support?

### ISSUE THREAD

**Issue by ThePrimeagen** [stsewd/fzf-checkout.vim#23]
What do you think about adding rebase support?  I think it would be nice to fzf the branch I am going to rebase on.  Is this a direction you wish to go?

**Comment by stsewd** [comment]
Yeah, I think it would be a nice addition. I usually just do `:Git rebase master`, but I see this being useful, also merge. I may hold off till I find a good way to hook any action https://github.com/stsewd/fzf-checkout.vim/issues/22 instead of creating more options

**Comment by stsewd** [comment]
I have refactored the plugin, now you can define your own actions! What do you think about these defaults for rebase?

```vim
let g:fzf_branch_actions = {
      \ 'rebase': {
      \   'prompt': 'Rebase> ',
      \   'execute': 'echo system("{git} rebase {branch}")',
      \   'multiple': v:false,
      \   'keymap': 'ctrl-r',
      \   'required': ['branch'],
      \   'confirm': v:true,
      \ },
      \}
```

Specially the ctrl-r keymap and if we should ask for confirmation before doing the rebase.

**Comment by stsewd** [comment]
Closed by https://github.com/stsewd/fzf-checkout.vim/pull/30

**Comment by ThePrimeagen** [comment]
btw, @stsewd i have used it, it was awesome!

Great job!
