### ISSUE TITLE
[Question] Checkout and create if needed?

### ISSUE THREAD

**Issue by alex-popov-tech** [stsewd/fzf-checkout.vim#29]
Thanks for the awesome plugin!
Question - usually branches are not that heavy to pull/checkout in, so would it be possible to do something like 'checkout in branch if exist locally, if not create branch and checkout there' ? To use that instead of two commands - checkout + create

**Comment by stsewd** [comment]
> To use that instead of two commands - checkout + create

Not sure to understand that. Currently, to create a branch you can do `:GBranches` and write a name and press `ctrl-n` or you can do `:GBranches create` and write a name and press enter. Both methods will create the branch and checkout to it (git branch -b branch is executed)

**Comment by alex-popov-tech** [comment]
hey, thanks for the quick response @stsewd !
the point is - i want to be able to do `:GBranches` and then just `enter` to checkout (if have this one locally) OR checkout -b (if i don't)

**Comment by stsewd** [comment]
I see, with the latest version you can do

```vim
let g:fzf_branch_actions = {
      \ 'checkout': {
      \   'execute': 'echo system("{git} checkout " . (empty("{branch}") ? "-b {input}" : "{branch}"))',
      \   'required': [],
      \ },
      \}
```

But it falls back only if you haven't selected an item, that means you need to write something that doesn't list anything. I don't know if there is something to mark explicitly an option in fzf.

**Comment by alex-popov-tech** [comment]
thanks, will try it out!
