### ISSUE TITLE
Results are no longer sorted after filtering results

### ISSUE THREAD

**Issue by DanielPower** [stsewd/fzf-checkout.vim#39]
Using the option to sort results by commit date:
`let g:fzf_checkout_git_options = '--sort=-committerdate'`

This works when the filter string is empty. But once you type to filter the results, they are no longer sorted by commit date. Backspacing until the filter string is empty will cause the results to become sorted again.

**Comment by stsewd** [comment]
I think this is an option from fzf, I'll see if I can make this an option/event.

- `--no-sort`
- `--bind=ctrl-s:toggle-sort`

**Comment by stsewd** [comment]
I've been using this option for a while, and feels correct to have it by default, if someone finds this odd please let me know, so I can implement this as an option instead.
