### ISSUE TITLE
Cannot checkout to first branch 

### ISSUE THREAD

**Issue by mars90226** [stsewd/fzf-checkout.vim#4]
First branch has `-e` before the branch name and cannot checkout.

Screenshot:
![fzf_checkout_dash_e](https://user-images.githubusercontent.com/1523214/79035188-a3dfaf80-7bee-11ea-8ae5-2165fe6def17.png)

Remove `-e` in `l:source` in `fzf_checkout#list()` seems to fix this bug.

**Comment by stsewd** [comment]
what OS and shell are you using?

**Comment by mars90226** [comment]
OS: Ubuntu 18.04
shell: bash 4.4.20(1)-release

**Comment by stsewd** [comment]
So, looks like I'll need to research a little more here.

Bash 5.0.11, bash 4.4.20 and zsh. All of them give different results with `echo -e '\\n'`, `echo '\\n'`, `echo '\n'` and `echo -e '\n'`

**Comment by stsewd** [comment]
Looks like printf has a more deterministic behavior than echo https://stackoverflow.com/questions/8467424/echo-newline-in-bash-prints-literal-n/8467449#8467449 I'll try that later

**Comment by stsewd** [comment]
@mars90226 could you please check if https://github.com/stsewd/fzf-checkout.vim/pull/5 solves the problem for you?

It works for me in zsh and bash ` 5.0.11`

**Comment by mars90226** [comment]
Sorry for the late reply. It works now, thank you!

**Comment by mars90226** [comment]
Sorry, I think I should close issue after #5 is merged. Or you can close it if it's merged.

**Comment by stsewd** [comment]
@mars90226 thanks it's on master now!
