### ISSUE TITLE
How to override the mapping checkout locally? 

### ISSUE THREAD

**Issue by tammarut** [stsewd/fzf-checkout.vim#40]
### About this feature

> Press `alt-enter` to track a remote branch locally (origin/foo becomes foo)

I want to override the mapping to track a branch with ctrl-t 
but it won't work❌
```
let g:fzf_branch_actions = {
      \ 'track a remote': {'keymap': 'ctrl-t'},
      \}
```

**Comment by stsewd** [comment]
The setting should be


```
let g:fzf_branch_actions = {
      \ 'track': {'keymap': 'ctrl-t'},
      \}
```
