### ISSUE TITLE
Creating a new branch with control-n is counter-intuitive with fzf

### ISSUE THREAD

**Issue by etiennebatise** [stsewd/fzf-checkout.vim#41]
This is more of a feedback than an issue.

By default, [basic fzf navigation](https://github.com/junegunn/fzf#using-the-finder) (going up and down) is done with 2 possible keyboard shortcut pairs:
  - `CTRL-J` & `CTRL-K` 
or 
  - `CTRL-N` & `CTRL-P` 

As you might have guessed, I’m a user of the latter. Muscle memory being what it is, I have created countless garbage branches when browsing throught branches using this **wonderful** plugin. I think it'd be great to add a section to the docs pointing out this incompatibility with the default shortcut, and suggesting an alternative. For instance, as the `git` command is `git checkout -b ...`, I have it configured with `ctrl-b`:

```
let g:fzf_branch_actions = {
      \ 'create': {'keymap': 'ctrl-b'}
}

```

**Comment by stsewd** [comment]
Oh, this is also overrides the navigation through history actually (`g:fzf_history_dir`). I'm fine changing the defautl to `ctrl-c` or `ctrl-b`

**Comment by etiennebatise** [comment]
I wonder if `ctrl-c` isn’t cancelling the `fzf` action 🤔

**Comment by stsewd** [comment]
`ctrl-c` and `ctrl-q` are for cancelling yes.
