### ISSUE TITLE
Opened Buffers aren't reloaded when branch is changed

### ISSUE THREAD

**Issue by kernelheap** [stsewd/fzf-checkout.vim#44]
When :GBranches is run and a branch is selected, although the branch is checked out correctly but the already opened buffers in vim don't auto reload.

**Comment by stsewd** [comment]
Hi, I think this should be an option from the editor (reload when the file had changed), this is done automatically with the latest nightly version from neovim.

**Comment by jacktuck** [comment]
How about in Vim?

**Comment by stsewd** [comment]
@jacktuck hi, I think this option can help https://github.com/stsewd/fzf-checkout.vim/issues/47#issuecomment-791845487
