### ISSUE TITLE
Alt + Enter to track and checkout branch not working

### ISSUE THREAD

**Issue by smithshelke** [stsewd/fzf-checkout.vim#45]
Im using vim on MacOS BigSur.
Expected : 
When I do :GBranches, and find origin/foo branch, I should be able to Alt-Enter and goto the locally tracked branch of origin/foo that is foo. 
Output : 
When I do :GBranches, and find origin/foo branch, I checkout to the origin/foo branch
 
Either Alt (Option on Mac) key bindings dont work on vim on mac or might be some other issue

**Comment by stsewd** [comment]
Sorry for the late reply! I don't use mac, so can't be sure, but maybe it is related to the keybinding yeah, you can try overriding it with

```vim
let g:fzf_tag_actions = {
      \ 'track': {'keymap': 'ctrl-space'},
      \}
```


You can see all available keys in `man fzf`
