### ISSUE TITLE
Switching branch does not refresh open buffers

### ISSUE THREAD

**Issue by morpheusthewhite** [stsewd/fzf-checkout.vim#47]
When switching branch open buffers associated with files that are affected by the switch do not change. They should instead read again from the filesystem the file content

**How to reproduce**:
- Open a file that is different across branches with `vim`
- Switch branch using this plugin
-> Buffer did not change

**Comment by stsewd** [comment]
Hi, as mentioned in https://github.com/stsewd/fzf-checkout.vim/issues/44, the editor should be able to detect changes outside the file. This works with neovim nightly, I think vim has an option for that as well (`set autoread`) https://unix.stackexchange.com/questions/149209/refresh-changed-content-of-file-opened-in-vim.
