### ISSUE TITLE
How to change the default layout?

### ISSUE THREAD

**Issue by LukaszBielsko** [stsewd/fzf-checkout.vim#48]
In order to make fzf-checkout look consistent with fzf I'd like to change the default layout. 
I'd like to have the input field on top rather then on bottom. 

Went through thed docs and couldn't find anything. 
Poked around in the code, but I ain't vim script literate :)

**Comment by LukaszBielsko** [comment]
In order to change the layout from bottom to top I added `--layout=reverse` in `l:fzf_options` variable in `fzf_checkout.vim`

**Comment by stsewd** [comment]
Using the `g:fzf_layout` option should work, as the plugin calls fzf#wrap, but maybe it doesn't?

```
                                      *fzf-global-options-supported-by-fzf#wrap*

 - `g:fzf_layout`
 - `g:fzf_action`
   - Works only when no custom `sink` (or `sink*`) is provided
     - Having custom sink usually means that each entry is not an ordinary
       file path (e.g. name of color scheme), so we can't blindly apply the
       same strategy (i.e. `tabedit some-color-scheme` doesn't make sense)

```

**Comment by LukaszBielsko** [comment]
My `fzf` config is pretty messed up, so maybe that was the case :)
