### ISSUE TITLE
Show status of the working directory

### ISSUE THREAD

**Issue by heroin-moose** [stsewd/fzf-checkout.vim#53]
If you have dirty working directory some checkouts will fail, advising you to either commit or to stash  your changes. Currently you cannot spot a failed checkout without manually checking current branch afterwards. This additional info may give you a hint earlier without the need to call `:Git status` manually after you discovered that you're in the same branch as before. Also it's a good hint all by itself, forgetting to commit bites me from time to time.

**Comment by stsewd** [comment]
> Currently you cannot spot a failed checkout without manually checking current branch afterwards

With the current default the error will be printed when you press enter. The printed error requires you to press enter "Press ENTER or type command to continue" so it doesn't just disappear. I think showing the status may be out of scope of this plugin.

**Comment by jacktuck** [comment]
I think this fails silently in Vim (v8.2) but works in nvim (I tested with identical vimrc and plugins).
