### ISSUE TITLE
Plugin checks out remote branch with head detached, instead of tracking

### ISSUE THREAD

**Issue by robcsi** [stsewd/fzf-checkout.vim#57]
Hello,

I have reconfigured the alt-enter for tracking shortcut to ctrl-t because alt-enter overlapped with another key map. So, with that it seems to execute checkout instead of tracking.

The output message is 
     
     HEAD is now at <commit> 'commit message'
     
instead of 
     
     Branch '...' set up to track remote branch '...' from 'origin'.
     Switched to a new branch '...'
     
Could this be a mapping problem in nvim?

Thanks

**Comment by robcsi** [comment]
Never mind, my bad.

**Comment by khang-11** [comment]
> Never mind, my bad.

How did you end up fixing this?

**Comment by robcsi** [comment]
Sorry, I don't remember. I don't use the plugin anymore.
