### ISSUE TITLE
Error when checking out a branch

### ISSUE THREAD

**Issue by Coffei** [stsewd/fzf-checkout.vim#6]
Hi,
I have a strange problem with this plugin, when I try to checkout any branch I get the following error
```
error: pathspec ''master'' did not match any file(s) known to git
```

Trying the command that appears in the status (`git checkout 'master'` in this case) in bash works fine. I have GIT in the following version `git version 2.26.2`.

Any idea what could be causing this?

**Comment by Coffei** [comment]
I get the same error when running `git checkout -- master`. Maybe the plugin inserts some chars between `checkout` and the branch name that could be interpreted in a similar way?

**Comment by stsewd** [comment]
What shell and version are you using? (bash, zsh, etc)

**Comment by Coffei** [comment]
`GNU bash, version 5.0.11(1)-release`

**Comment by stsewd** [comment]
I can't replicate with bash 5.0.11. I'm using fedora and Neovim v0.5.0-519-g74fed7d50

**Comment by stsewd** [comment]
Also, can you check the output of `:echo shellescape('master')`. I get `'master'`.

**Comment by Coffei** [comment]
I get `'master'` too. I'm also on Fedora (32) but I'm using vim 8.2. Is there any way to get the commands the plugin is executing, so that I can inspect what exactly is being executed?
I also tried running without other plugins and with clean `.vimrc` but I can still reproduce this in both cases.

**Comment by Coffei** [comment]
Hmm.. It seems it's the quotes causing the problem. The plugin generates this command `split | terminal git checkout 'master'`, executing the same directly in VIM shows the same error message. Without quotes it works fine.

**Comment by Coffei** [comment]
Using `!` instead of `terminal` to execute the command works fine for me, though not sure if that's a solution you'd consider. I can submit a PR if that works for you.

**Comment by stsewd** [comment]
I wanted to give it a try to `execute()` (as an alternative to terminal), but first let me see if there is a way to make terminal work with vim

**Comment by stsewd** [comment]
@Coffei I have added a new setting to allow users to specify how to checkout the branch https://github.com/stsewd/fzf-checkout.vim#gfzf_checkout_execute

It defaults to use `system()`, I think that works for both, vim and neovim. Let me know if that fixed the problem for you.

**Comment by Coffei** [comment]
Both `system` and `bang` work great for me. Thanks for the fix and this useful plugin! :)
