### ISSUE TITLE
Error when call :GBranches

### ISSUE THREAD

**Issue by jedi-vim** [stsewd/fzf-checkout.vim#60]
I'm using Debian9 and git 2.11.0, when i call :GBranches i've got the error bellow
```
error: unknown option `format=%(color:yellow bold)%(refname:short)  %(color:reset)%(color:green)%(subject) %(color:reset)%(color:green dim italic)
%(committerdate:relative) %(color:reset)%(color:blue)-> %(objectname:short)'
usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
   or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
   or: git branch [<options>] [-r] (-d | -D) <branch-name>...
   or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
   or: git branch [<options>] [-r | -a] [--points-at]

Generic options
    -v, --verbose         show hash and subject, give twice for upstream branch
    -q, --quiet           suppress informational messages
    -t, --track           set up tracking mode (see git-pull(1))
    --set-upstream        change upstream info
    -u, --set-upstream-to <upstream>
```
    
I think my git version does not support [--format option](https://github.com/stsewd/fzf-checkout.vim/blob/master/autoload/fzf_checkout.vim#L3) , so theres a way to override this option throughout `init.vim`?

**Comment by stsewd** [comment]
> so theres a way to override this option throughout init.vim?

Sorry, this plugin makes use of the format option in order to output the branches names in a specific order, it may break the plugin if changed, you can try removing it and see if it works.

And you are right, the `--format` option was added in 2.13.7 https://git-scm.com/docs/git-branch/2.13.7

**Comment by stsewd** [comment]
The README now mentions that `git >=2.13.7` is required. I could consider adding support for old versions of git if someone wants to create a PR.
