### ISSUE TITLE
Correct branch name

### ISSUE THREAD

**Issue by hanh090** [stsewd/fzf-checkout.vim#7]
When I use this plugin in my environment: Ubuntu 20.4, fzf 0.20, vim 8, I can not checkout. Rootcause is this line https://github.com/stsewd/fzf-checkout.vim/blob/befc1601b785c59c53ce9357b4db9851a46f15ef/autoload/fzf_checkout.vim#L3 return wrong result. Expectation: branch name, Actual: whole line except the the commit one.
For example:
![Screenshot from 2020-06-10 21-16-22](https://user-images.githubusercontent.com/3643657/84279023-ae231900-ab5f-11ea-817e-cc40025d0771.png)

I do not sure about your regex yet, but what do you think if we change to split for more readable?
my proposal change to `split(a:line)[0]`

**Comment by stsewd** [comment]
That's more clear, thanks for the suggestions. Let me know if it works now!

**Comment by hanh090** [comment]
it works now
