### ISSUE TITLE
Create a branch

### ISSUE THREAD

**Issue by jet8a** [stsewd/fzf-checkout.vim#8]
It would be very convenient to create a branch if it didn't exist in the result.

![image](https://user-images.githubusercontent.com/14956407/84473408-4cf76480-ac89-11ea-8131-a01b45adb6ec.png)

**Comment by stsewd** [comment]
I have though about this a couple of times. I'm not sure if it's possible. Maybe the `--print-query` option may help with this, that way we receive the query and can create a branch if a key is pressed.

**Comment by stsewd** [comment]
I'll take a look at implementing this by next week.

**Comment by stsewd** [comment]
Ok, I have implemented this. You can create a branch with the query as name by pressing `ctrl-n` (you can change this). Let me know if that works as expected :)

**Comment by jet8a** [comment]
Yes, thank you
