### ISSUE TITLE
Remote branches do not show up

### ISSUE THREAD

**Issue by DanilaMihailov** [stsewd/fzf-checkout.vim#9]
When I execute `:GCheckout` I only see local branches, even though I can see all branches by doing `git branch --all`.

I see you using `git branch --all` as well [here](https://github.com/stsewd/fzf-checkout.vim/blob/master/autoload/fzf_checkout.vim#L69), so I have no idea why it does not work.

I use:
NVIM v0.4.3
alacritty 0.4.3 (c723247)
macOS Catalina 10.15.5

Also checked it out in builtin macOS terminal and minimal vimrc.

```
call plug#begin()
Plug 'junegunn/fzf', { 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'stsewd/fzf-checkout.vim'
call plug#end()
```

**Comment by stsewd** [comment]
Thanks for reporting, the bug is the filter when there isn't a previous a branch/tag. A workaround is to do `git checkout master` or whatever first. I'll get a patch soon.

**Comment by stsewd** [comment]
Please, let me know if it works now

**Comment by DanilaMihailov** [comment]
I am sorry, but it is still not working. I added 

```
echo l:source
```
to fzf-checkout.vim:116 to see what command fzf going to execute. And then run it myself and got error.

```
printf "$(git branch --all --color=always --sort=refname:short --format='%(color:yellow bold)%(refname:short)  %(color:reset)%(color:green)%(subject) %(color:reset)%(color:green dim italic)%(committerdate:relative) %(color:reset)%(color:blue)-> %(objectname:short)'  --list master)"\\n"$(git branch --all --color=always --sort=refname:short --format='%(color:yellow bold)%(refname:short)  %(color:reset)%(color:green)%(subject) %(color:reset)%(color:green dim italic)%(committerdate:relative) %(color:reset)%(color:blue)-> %(objectname:short)'  | sed -r -e "/^\x1b\[1;33mmaster\s.*$/d" -e "/^\x1b\[1;33mmaster\s.*$/d" -e "/^\x1b\[1;33m(origin\/HEAD)|(HEAD)/d")" |  sed "/^\s*$/d"

sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
master  Add whitespace after dropped file paths 2 weeks ago -> e009869
```

There is no `-r` flag in macOS sed, but there is `-E` flag that seems to be doing the same.
From manual:
```
     -E      Interpret regular expressions as extended (modern) regular expressions rather than basic regular expressions (BRE's).  The re_format(7) manual page fully describes both formats.
```

So I replaced flag and it works. I can do merge request later today if you want :)
